[toolchain]
package_manager = "yarn"
channel = "1.79.0"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
market_system = "APESCaeLW5RuxNnpNARtDZnSgeVFC5f37Z3VFNKupJUS"

[programs.devnet]
market_system = "APESCaeLW5RuxNnpNARtDZnSgeVFC5f37Z3VFNKupJUS"

[programs.mainnet]
market_system = "APESCaeLW5RuxNnpNARtDZnSgeVFC5f37Z3VFNKupJUS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://mainnet.helius-rpc.com/?api-key=4a7d2ddd-3e83-4265-a9fb-0e4a5b51fd6d"
wallet = "./APEShoBNNvnM4JV6pW51vb8X4Cq6ZeZy6DqfjmTu6j4z.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
